# Generated by Django 5.0.4 on 2024-06-02 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidayRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='dateFrom',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='vacation',
            name='dateTo',
            field=models.DateField(default=datetime.date(2024, 6, 2)),
        ),
    ]
