# Generated by Django 5.0.4 on 2024-06-02 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidayRM', '0002_vacation_datefrom_vacation_dateto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='dateFrom',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 13, 37, 56, 201386, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='dateTo',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 13, 37, 56, 201386, tzinfo=datetime.timezone.utc)),
        ),
    ]
