# Generated by Django 5.0.4 on 2024-06-02 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidayRM', '0003_alter_vacation_datefrom_alter_vacation_dateto'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('usertype', models.IntegerField(choices=[(1, 'ADMIN'), (2, 'USER')])),
            ],
        ),
        migrations.AlterField(
            model_name='vacation',
            name='dateFrom',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 19, 8, 3, 496678, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='dateTo',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 19, 8, 3, 496678, tzinfo=datetime.timezone.utc)),
        ),
    ]
