# Generated by Django 5.0.4 on 2024-06-02 22:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidayRM', '0004_user_alter_vacation_datefrom_alter_vacation_dateto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='vacation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacation',
            name='dateFrom',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 22, 8, 32, 459339, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='dateTo',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 22, 8, 32, 459339, tzinfo=datetime.timezone.utc)),
        ),
    ]
