# Generated by Django 5.0.4 on 2024-06-03 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidayRM', '0005_delete_user_vacation_user_alter_vacation_datefrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='dateFrom',
            field=models.DateField(default=datetime.datetime(2024, 6, 3, 20, 40, 24, 306689, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='dateTo',
            field=models.DateField(default=datetime.datetime(2024, 6, 3, 20, 40, 24, 306689, tzinfo=datetime.timezone.utc)),
        ),
    ]
